name: pusakatest-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  automation-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}

    - name: cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules-${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}

    - name: cucumber-reports env variable
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      run: export CUCUMBER_PUBLISH_TOKEN=$PUBLISH_TOKEN

    - name: install dependencies
      run: npm install

    - name: test
      run: npm run test-publish

    - name: archive report
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-report
        path: cucumber-report.html